format = """\
$conda\
$singularity\
$kubernetes\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$package\
$python\
$ruby\
$julia\
$cmd_duration\
$line_break\
$time\
$character\
"""

[character]
success_symbol = "ğŸ®"
error_symbol = "ğŸ”¥"
vicmd_symbol = "ğŸ”®"

[conda]
symbol = "ğŸ…’ "
# color = "bold blue"
ignore_base = false
format = "[$symbol$environment]($style) "

[singularity]
symbol = "ğŸ“¦ "

[python]


[julia]
format = ":: [$symbol($version)]($style) "
